<#
.SYNOPSIS
    Builds PlanetaryAnomalies.dll.

.DESCRIPTION
    Compiles with the C# compiler that ships with the .NET Framework -- already on every
    Windows machine -- so there is no SDK to install and no NuGet restore.

    It compiles against the game's own assemblies (/nostdlib+ plus an explicit reference to
    the game's mscorlib), which is what a Unity mod should bind to anyway. That does mean
    C# 5 language features only: no string interpolation, no ?., no expression-bodied members.

.EXAMPLE
    .\scripts\build.ps1
.EXAMPLE
    .\scripts\build.ps1 -Install
#>
[CmdletBinding()]
param(
    # DSP install folder. Discovered from Steam if omitted.
    [string]$GameDir,

    # BepInEx folder to reference. Discovered from the Gale profiles if omitted.
    [string]$BepInExDir,

    # Gale profile name, when more than one profile has BepInEx installed.
    [string]$ProfileName,

    # Copy the result into the BepInEx plugins folder afterwards.
    [switch]$Install
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'common.ps1')

$repoRoot = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $repoRoot 'build'
$outDll = Join-Path $outDir 'PlanetaryAnomalies.dll'

$GameDir = Get-DspDir -Override $GameDir
$managed = Get-ManagedDir -GameDir $GameDir
$BepInExDir = Get-BepInExDir -Override $BepInExDir -ProfileName $ProfileName -GameDir $GameDir
$csc = Get-CscPath

Write-Host "Game:    $GameDir"
Write-Host "BepInEx: $BepInExDir"
Write-Host "Compiler: $csc"

$references = @(
    (Join-Path $managed 'mscorlib.dll')
    (Join-Path $managed 'System.dll')
    (Join-Path $managed 'System.Core.dll')
    # BepInEx and UnityEngine.CoreModule both surface netstandard-typed members.
    (Join-Path $managed 'netstandard.dll')
    (Join-Path $managed 'Assembly-CSharp.dll')
    (Join-Path $managed 'UnityEngine.dll')
    (Join-Path $managed 'UnityEngine.CoreModule.dll')
    # UnityEngine.UI: the planet detail panel's brief is a UnityEngine.UI.Text.
    (Join-Path $managed 'UnityEngine.UI.dll')
    (Join-Path $BepInExDir 'core\BepInEx.dll')
    (Join-Path $BepInExDir 'core\0Harmony.dll')
)

foreach ($reference in $references) {
    if (-not (Test-Path $reference)) { throw "Missing reference assembly: $reference" }
}

$sources = @(Get-ChildItem (Join-Path $repoRoot 'src') -Filter *.cs -Recurse | ForEach-Object { $_.FullName })
if ($sources.Count -eq 0) { throw "No .cs files found under $repoRoot\src." }

if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

# --- stamp the version into the assembly itself ------------------------------------------------
#
# Without this the DLL reports 0.0.0.0 in its file properties, which was true of every release up
# to and including 0.4.0. Nothing functional depended on it -- BepInEx and Gale read the version
# from the [BepInPlugin] attribute -- but a file that does not say what it is makes "which build is
# this?" harder to answer than it should be, and that question has already cost an hour here.
#
# Generated rather than committed, so Plugin.cs stays the single declaration. package.ps1 already
# enforces that it agrees with the Thunderstore manifest; a third copy would be a third thing to
# forget.
$pluginSource = Join-Path $repoRoot 'src\Plugin.cs'
$pluginText = [System.IO.File]::ReadAllText($pluginSource)
if ($pluginText -notmatch 'PluginVersion\s*=\s*"([^"]+)"') {
    throw "Could not read PluginVersion from '$pluginSource'."
}
$pluginVersion = $Matches[1]

# AssemblyVersion insists on four parts; the plugin declares three, as Thunderstore expects.
$assemblyVersion = if (($pluginVersion -split '\.').Count -eq 3) { "$pluginVersion.0" } else { $pluginVersion }

$generatedInfo = Join-Path $outDir 'AssemblyInfo.g.cs'
$generatedText = @"
// Generated by scripts/build.ps1 from PluginVersion in src/Plugin.cs. Do not edit; do not commit.
using System.Reflection;

[assembly: AssemblyTitle("Planetary Anomalies")]
[assembly: AssemblyProduct("Planetary Anomalies")]
[assembly: AssemblyVersion("$assemblyVersion")]
[assembly: AssemblyFileVersion("$assemblyVersion")]
[assembly: AssemblyInformationalVersion("$pluginVersion")]
"@
[System.IO.File]::WriteAllText($generatedInfo, $generatedText, (New-Object System.Text.UTF8Encoding($false)))
$sources += $generatedInfo

Write-Host "Version: $pluginVersion (assembly $assemblyVersion)"
Write-Host "Compiling $($sources.Count) source file(s)..."

$cscArgs = @(
    '/nologo'
    # /noconfig: without it csc.rsp adds the machine's own System.dll and System.Core.dll,
    # which collide with the game's copies of the same assembly identities.
    '/noconfig'
    '/target:library'
    '/platform:x64'
    '/optimize+'
    '/debug:pdbonly'
    '/warnaserror-'
    '/nostdlib+'
    "/out:$outDll"
)
$cscArgs += ($references | ForEach-Object { "/reference:$_" })
$cscArgs += $sources

& $csc $cscArgs
if ($LASTEXITCODE -ne 0) { throw "Compilation failed (csc exit code $LASTEXITCODE)." }

$built = Get-Item $outDll
Write-Host "Built $($built.FullName) ($($built.Length) bytes)" -ForegroundColor Green

if ($Install) {
    & (Join-Path $PSScriptRoot 'install.ps1') -GameDir $GameDir -BepInExDir $BepInExDir
}
